# Generated by Django 5.0.6 on 2024-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
