# Generated by Django 5.0.6 on 2024-05-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_alter_blogpost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.FileField(null=True, upload_to='Blogs/images'),
        ),
    ]
